# This is a basic workflow to help you get started with Actions

name: Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macOS-Chez:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Checkout submodules
      uses: chris-short/github-action-git-submodules@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez

    - run: chez --libdirs ./:./thunderchez ./tests.ss

  Linux-Chez:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Checkout submodules
      uses: chris-short/github-action-git-submodules@master

    - name: use Setup-Scheme
      uses: guenchi/setup-scheme@master
      with:
        implementation: chez

    - run: scheme --libdirs ./:./thunderchez ./tests.ss